# Generated by Django 3.2.21 on 2023-09-18 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tours.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=100)),
                ('tour_description', models.TextField(default='No description available', validators=[django.core.validators.MaxLengthValidator(limit_value=500, message='Description is too long.')], verbose_name='Tour Experience Description')),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tour_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tour_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('street_address1', models.CharField(max_length=25)),
                ('street_address2', models.CharField(blank=True, max_length=25, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=60, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=10, validators=[tours.validators.validate_country])),
                ('tour_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.category')),
            ],
        ),
    ]
