# Generated by Django 3.2.21 on 2023-09-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20230920_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.Category'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='tour_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour', to='tours.category'),
        ),
    ]
