# Generated by Django 3.2.21 on 2023-09-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_auto_20230923_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='tour_category',
        ),
    ]
