# Generated by Django 3.2.21 on 2023-09-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_remove_tours_tour_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='category',
            new_name='tour_category',
        ),
    ]
