# Generated by Django 3.2.21 on 2023-09-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_rename_category_tours_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='max_attendees',
            field=models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=4, help_text='Maximum number of attendees per group'),
        ),
    ]
