# Generated by Django 3.2.21 on 2023-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_tours_max_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='max_capacity',
            field=models.PositiveIntegerField(choices=[(8, '8'), (12, '12'), (16, '16'), (20, '20')], default=12, help_text='Maximum capacity per experience'),
        ),
    ]
