# Generated by Django 3.2.21 on 2023-10-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tours_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tours',
            name='tour_category',
            field=models.ManyToManyField(blank=True, help_text='Hold ctrl/cmmd key to select more than one', related_name='tours', to='tours.Category'),
        ),
    ]
