# Generated by Django 3.2.21 on 2023-10-10 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile_number',
            field=models.CharField(max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_of_booking',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
