# Generated by Django 3.2.21 on 2023-10-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231010_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='test',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
