# Generated by Django 3.2.21 on 2023-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_basket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
